{
 "title": "esper_analysis_init",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Captured Issues",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(esper_query_matches_total) by (query_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed Events",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{topic!=\"dynatraceEvents\"}) by (topic) - 1 or\r\nsum(kafka_consumergroup_current_offset{topic=\"dynatraceEvents\"}) by (topic) - 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployed Analytics Queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "analytics_queries_deployed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions In Esper Listeners ",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(listener_exceptions_total) by (query_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Esper Consumed Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 8 },
   "targets": [
    { "expr": "rate(esper_events_total[1m])", "legendFormat": "Events per minute" }
   ]
  },
  {
   "title": "Deployed Analysis Queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "analysis_queries_deployed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analysis Queries Deployment Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(query_deployment_errors_total) by (query_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}